[project]
name = "llm-zoomcamp-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Guy Shargorodsky", email = "shargo501@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "google-genai>=2.14.0",
    "jupyter>=1.1.1",
    "minsearch>=0.2.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
]

[project.scripts]
llm-zoomcamp-2026 = "llm_zoomcamp_2026:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
