[project]
name = "llm-zoomcamp-onnx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Guy Shargorodsky", email = "shargo501@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "minsearch>=0.2.0",
    "numpy>=2.5.3",
    "onnxruntime>=1.29.0",
    "tokenizers>=0.23.2",
    "tqdm>=4.70.0",
]

[project.scripts]
llm-zoomcamp-onnx = "llm_zoomcamp_onnx:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "huggingface-hub>=1.30.0",
    "jupyter>=1.1.1",
]
